FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json ./
RUN npm install --legacy-peer-deps

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED 1
# In developer compose we run npm run dev directly. If compiling production:
# RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV development
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

COPY --from=builder /app ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
