"""initial_schema

Revision ID: 21b492085cc3
Revises: 
Create Date: 2026-07-21 08:00:42.164089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '21b492085cc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('agent_collaboration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('session_uuid', sa.String(length=36), nullable=False),
    sa.Column('collaboration_type', sa.String(length=100), nullable=False),
    sa.Column('initiator', sa.String(length=100), nullable=False),
    sa.Column('collaborators', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('downtime_saved_estimate', sa.Float(), nullable=False),
    sa.Column('cost_saved_estimate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_collaboration_id'), 'agent_collaboration', ['id'], unique=False)
    op.create_index(op.f('ix_agent_collaboration_session_uuid'), 'agent_collaboration', ['session_uuid'], unique=False)
    op.create_index(op.f('ix_agent_collaboration_uuid'), 'agent_collaboration', ['uuid'], unique=True)
    op.create_table('agent_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memory_agent_name'), 'agent_memory', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_memory_id'), 'agent_memory', ['id'], unique=False)
    op.create_index(op.f('ix_agent_memory_uuid'), 'agent_memory', ['uuid'], unique=True)
    op.create_table('agent_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('session_uuid', sa.String(length=36), nullable=True),
    sa.Column('sender', sa.String(length=100), nullable=False),
    sa.Column('receiver', sa.String(length=100), nullable=False),
    sa.Column('message_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_id'), 'agent_messages', ['id'], unique=False)
    op.create_index(op.f('ix_agent_messages_receiver'), 'agent_messages', ['receiver'], unique=False)
    op.create_index(op.f('ix_agent_messages_sender'), 'agent_messages', ['sender'], unique=False)
    op.create_index(op.f('ix_agent_messages_session_uuid'), 'agent_messages', ['session_uuid'], unique=False)
    op.create_index(op.f('ix_agent_messages_uuid'), 'agent_messages', ['uuid'], unique=True)
    op.create_table('agent_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('tasks_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('avg_response_time', sa.Float(), nullable=False),
    sa.Column('average_confidence', sa.Float(), nullable=False),
    sa.Column('utilization_rate', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_metrics_agent_name'), 'agent_metrics', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_metrics_id'), 'agent_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_agent_metrics_uuid'), 'agent_metrics', ['uuid'], unique=True)
    op.create_table('discovery_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('affected_assets', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('recommended_actions', sa.Text(), nullable=False),
    sa.Column('expected_savings', sa.Float(), nullable=False),
    sa.Column('finding_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_findings_id'), 'discovery_findings', ['id'], unique=False)
    op.create_index(op.f('ix_discovery_findings_uuid'), 'discovery_findings', ['uuid'], unique=True)
    op.create_table('enterprise_kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('plant_health_score', sa.Float(), nullable=False),
    sa.Column('ai_confidence_score', sa.Float(), nullable=False),
    sa.Column('knowledge_health_score', sa.Float(), nullable=False),
    sa.Column('compliance_readiness_score', sa.Float(), nullable=False),
    sa.Column('maintenance_readiness_score', sa.Float(), nullable=False),
    sa.Column('asset_reliability_score', sa.Float(), nullable=False),
    sa.Column('operational_readiness_score', sa.Float(), nullable=False),
    sa.Column('downtime_risk_score', sa.Float(), nullable=False),
    sa.Column('knowledge_growth_score', sa.Float(), nullable=False),
    sa.Column('continuous_learning_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_kpis_id'), 'enterprise_kpis', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_kpis_uuid'), 'enterprise_kpis', ['uuid'], unique=True)
    op.create_table('executive_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executive_metrics_id'), 'executive_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_executive_metrics_uuid'), 'executive_metrics', ['uuid'], unique=True)
    op.create_table('executive_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('report_name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('kpi_data', sa.Text(), nullable=False),
    sa.Column('financial_summary', sa.Text(), nullable=False),
    sa.Column('risk_summary', sa.Text(), nullable=False),
    sa.Column('recommendations_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executive_reports_id'), 'executive_reports', ['id'], unique=False)
    op.create_index(op.f('ix_executive_reports_uuid'), 'executive_reports', ['uuid'], unique=True)
    op.create_table('financial_impact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_impact_id'), 'financial_impact', ['id'], unique=False)
    op.create_index(op.f('ix_financial_impact_uuid'), 'financial_impact', ['uuid'], unique=True)
    op.create_table('learning_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('confidence_delta', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_events_id'), 'learning_events', ['id'], unique=False)
    op.create_index(op.f('ix_learning_events_uuid'), 'learning_events', ['uuid'], unique=True)
    op.create_table('model_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('recommendation_accuracy', sa.Float(), nullable=False),
    sa.Column('answer_quality', sa.Float(), nullable=False),
    sa.Column('citation_quality', sa.Float(), nullable=False),
    sa.Column('knowledge_graph_quality', sa.Float(), nullable=False),
    sa.Column('agent_collaboration_quality', sa.Float(), nullable=False),
    sa.Column('discovery_quality', sa.Float(), nullable=False),
    sa.Column('decision_success_rate', sa.Float(), nullable=False),
    sa.Column('evaluation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_evaluation_id'), 'model_evaluation', ['id'], unique=False)
    op.create_index(op.f('ix_model_evaluation_uuid'), 'model_evaluation', ['uuid'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_index(op.f('ix_organizations_uuid'), 'organizations', ['uuid'], unique=True)
    op.create_table('regulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('authority', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('clause_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulations_id'), 'regulations', ['id'], unique=False)
    op.create_index(op.f('ix_regulations_name'), 'regulations', ['name'], unique=True)
    op.create_index(op.f('ix_regulations_uuid'), 'regulations', ['uuid'], unique=True)
    op.create_table('risk_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('risk_category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('impact_description', sa.Text(), nullable=False),
    sa.Column('affected_assets', sa.String(length=255), nullable=False),
    sa.Column('financial_exposure', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_summary_id'), 'risk_summary', ['id'], unique=False)
    op.create_index(op.f('ix_risk_summary_uuid'), 'risk_summary', ['uuid'], unique=True)
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_id'), 'plants', ['id'], unique=False)
    op.create_index(op.f('ix_plants_uuid'), 'plants', ['uuid'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_uuid'), 'departments', ['uuid'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_uuid'), 'audit_logs', ['uuid'], unique=True)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_id'), 'email_verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_table('feedback_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('correction_text', sa.Text(), nullable=True),
    sa.Column('evidence_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_records_id'), 'feedback_records', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_records_uuid'), 'feedback_records', ['uuid'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_uuid'), 'notifications', ['uuid'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('user_organization_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_organization_grants_id'), 'user_organization_grants', ['id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_uuid'), 'workspaces', ['uuid'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_uuid'), 'chat_sessions', ['uuid'], unique=True)
    op.create_index(op.f('ix_chat_sessions_workspace_id'), 'chat_sessions', ['workspace_id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('asset_tag', sa.String(length=100), nullable=False),
    sa.Column('plant', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('installation_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('running_hours', sa.Float(), nullable=False),
    sa.Column('last_maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('next_maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('remaining_useful_life', sa.Float(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('failure_history', sa.Text(), nullable=True),
    sa.Column('inspection_reports', sa.Text(), nullable=True),
    sa.Column('open_work_orders', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_asset_tag'), 'equipment', ['asset_tag'], unique=True)
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_table('asset_comparison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('asset1_id', sa.Integer(), nullable=False),
    sa.Column('asset2_id', sa.Integer(), nullable=False),
    sa.Column('comparison_metrics', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset1_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset2_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_comparison_id'), 'asset_comparison', ['id'], unique=False)
    op.create_index(op.f('ix_asset_comparison_uuid'), 'asset_comparison', ['uuid'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('documents_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('related_equipment', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('decision_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('expected_benefit', sa.Text(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('estimated_downtime', sa.Float(), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('generated_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.String(length=105), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_recommendations_id'), 'decision_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_decision_recommendations_uuid'), 'decision_recommendations', ['uuid'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('plant_location', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('asset_tag', sa.String(length=100), nullable=True),
    sa.Column('equipment_name', sa.String(length=255), nullable=True),
    sa.Column('equipment_type', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model_number', sa.String(length=100), nullable=True),
    sa.Column('plant', sa.String(length=100), nullable=True),
    sa.Column('revision', sa.String(length=50), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('criticality', sa.String(length=50), nullable=True),
    sa.Column('keywords', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('version_group_id', sa.String(length=36), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('approval_status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_documents_asset_tag'), 'documents', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_department'), 'documents', ['department'], unique=False)
    op.create_index(op.f('ix_documents_document_name'), 'documents', ['document_name'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_plant_location'), 'documents', ['plant_location'], unique=False)
    op.create_index(op.f('ix_documents_uuid'), 'documents', ['uuid'], unique=True)
    op.create_index(op.f('ix_documents_version_group_id'), 'documents', ['version_group_id'], unique=False)
    op.create_table('expert_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('author_role', sa.String(length=100), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('failure_mode', sa.String(length=255), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('maintenance_type', sa.String(length=100), nullable=True),
    sa.Column('safety_risk', sa.String(length=100), nullable=True),
    sa.Column('process_stage', sa.String(length=100), nullable=True),
    sa.Column('weather_condition', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_keywords', sa.Text(), nullable=True),
    sa.Column('ai_entities', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_knowledge_id'), 'expert_knowledge', ['id'], unique=False)
    op.create_index(op.f('ix_expert_knowledge_uuid'), 'expert_knowledge', ['uuid'], unique=True)
    op.create_table('incident_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=True),
    sa.Column('incident_name', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('cause', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('prevention', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_records_id'), 'incident_records', ['id'], unique=False)
    op.create_index(op.f('ix_incident_records_uuid'), 'incident_records', ['uuid'], unique=True)
    op.create_table('knowledge_gap_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('gap_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_gap_records_id'), 'knowledge_gap_records', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_gap_records_uuid'), 'knowledge_gap_records', ['uuid'], unique=True)
    op.create_table('knowledge_twin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('operational_summary', sa.Text(), nullable=False),
    sa.Column('top_risks', sa.Text(), nullable=False),
    sa.Column('recommended_actions', sa.Text(), nullable=False),
    sa.Column('missing_knowledge', sa.Text(), nullable=False),
    sa.Column('compliance_readiness', sa.String(length=50), nullable=False),
    sa.Column('maintenance_readiness', sa.String(length=50), nullable=False),
    sa.Column('operational_confidence', sa.Float(), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=False),
    sa.Column('spare_parts', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_id')
    )
    op.create_index(op.f('ix_knowledge_twin_id'), 'knowledge_twin', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_twin_uuid'), 'knowledge_twin', ['uuid'], unique=True)
    op.create_table('maintenance_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('predicted_failure', sa.String(length=255), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('remaining_useful_life', sa.Float(), nullable=False),
    sa.Column('maintenance_priority', sa.String(length=50), nullable=False),
    sa.Column('suggested_maintenance_date', sa.DateTime(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_predictions_equipment_id'), 'maintenance_predictions', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_predictions_id'), 'maintenance_predictions', ['id'], unique=False)
    op.create_table('optimization_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_savings', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_opportunities_id'), 'optimization_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_opportunities_uuid'), 'optimization_opportunities', ['uuid'], unique=True)
    op.create_table('pattern_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('pattern_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('correlated_equipment_ids', sa.Text(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('correlation_coefficient', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_relationships_id'), 'pattern_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_pattern_relationships_uuid'), 'pattern_relationships', ['uuid'], unique=True)
    op.create_table('risk_discovery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('risk_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_discovery_id'), 'risk_discovery', ['id'], unique=False)
    op.create_index(op.f('ix_risk_discovery_uuid'), 'risk_discovery', ['uuid'], unique=True)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('vibration', sa.Float(), nullable=False),
    sa.Column('rpm', sa.Float(), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('current', sa.Float(), nullable=False),
    sa.Column('oil_level', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('runtime_hours', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_equipment_id'), 'sensor_readings', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_id'), 'sensor_readings', ['id'], unique=False)
    op.create_table('twin_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('knowledge_score', sa.Float(), nullable=False),
    sa.Column('snapshot_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twin_snapshot_id'), 'twin_snapshot', ['id'], unique=False)
    op.create_index(op.f('ix_twin_snapshot_uuid'), 'twin_snapshot', ['uuid'], unique=True)
    op.create_table('agent_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('chat_message_id', sa.Integer(), nullable=True),
    sa.Column('session_uuid', sa.String(length=36), nullable=False),
    sa.Column('agents_used', sa.Text(), nullable=False),
    sa.Column('reasoning_steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_execution_id'), 'agent_execution', ['id'], unique=False)
    op.create_index(op.f('ix_agent_execution_session_uuid'), 'agent_execution', ['session_uuid'], unique=False)
    op.create_index(op.f('ix_agent_execution_uuid'), 'agent_execution', ['uuid'], unique=True)
    op.create_table('compliance_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('regulation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('gaps_detected', sa.Text(), nullable=True),
    sa.Column('audit_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_audits_id'), 'compliance_audits', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_audits_uuid'), 'compliance_audits', ['uuid'], unique=True)
    op.create_table('decision_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['decision_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_evidence_id'), 'decision_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_decision_evidence_recommendation_id'), 'decision_evidence', ['recommendation_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=255), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_chunk_id'), 'document_chunks', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_table('knowledge_evolution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('evolution_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('recommended_update', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_evolution_id'), 'knowledge_evolution', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_evolution_uuid'), 'knowledge_evolution', ['uuid'], unique=True)
    op.create_table('knowledge_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('twin_id', sa.Integer(), nullable=False),
    sa.Column('documentation_coverage', sa.Float(), nullable=False),
    sa.Column('inspection_coverage', sa.Float(), nullable=False),
    sa.Column('maintenance_coverage', sa.Float(), nullable=False),
    sa.Column('expert_knowledge_coverage', sa.Float(), nullable=False),
    sa.Column('compliance_coverage', sa.Float(), nullable=False),
    sa.Column('incident_coverage', sa.Float(), nullable=False),
    sa.Column('recommendation_coverage', sa.Float(), nullable=False),
    sa.Column('overall_health_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['twin_id'], ['knowledge_twin.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twin_id')
    )
    op.create_index(op.f('ix_knowledge_health_id'), 'knowledge_health', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_health_uuid'), 'knowledge_health', ['uuid'], unique=True)
    op.create_table('recommendation_validation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('modified_action_text', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('confidence_delta', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engineer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['decision_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_validation_id'), 'recommendation_validation', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_validation_uuid'), 'recommendation_validation', ['uuid'], unique=True)
    op.create_table('workspace_documents',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_documents')
    op.drop_index(op.f('ix_recommendation_validation_uuid'), table_name='recommendation_validation')
    op.drop_index(op.f('ix_recommendation_validation_id'), table_name='recommendation_validation')
    op.drop_table('recommendation_validation')
    op.drop_index(op.f('ix_knowledge_health_uuid'), table_name='knowledge_health')
    op.drop_index(op.f('ix_knowledge_health_id'), table_name='knowledge_health')
    op.drop_table('knowledge_health')
    op.drop_index(op.f('ix_knowledge_evolution_uuid'), table_name='knowledge_evolution')
    op.drop_index(op.f('ix_knowledge_evolution_id'), table_name='knowledge_evolution')
    op.drop_table('knowledge_evolution')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_decision_evidence_recommendation_id'), table_name='decision_evidence')
    op.drop_index(op.f('ix_decision_evidence_id'), table_name='decision_evidence')
    op.drop_table('decision_evidence')
    op.drop_index(op.f('ix_compliance_audits_uuid'), table_name='compliance_audits')
    op.drop_index(op.f('ix_compliance_audits_id'), table_name='compliance_audits')
    op.drop_table('compliance_audits')
    op.drop_index(op.f('ix_agent_execution_uuid'), table_name='agent_execution')
    op.drop_index(op.f('ix_agent_execution_session_uuid'), table_name='agent_execution')
    op.drop_index(op.f('ix_agent_execution_id'), table_name='agent_execution')
    op.drop_table('agent_execution')
    op.drop_index(op.f('ix_twin_snapshot_uuid'), table_name='twin_snapshot')
    op.drop_index(op.f('ix_twin_snapshot_id'), table_name='twin_snapshot')
    op.drop_table('twin_snapshot')
    op.drop_index(op.f('ix_sensor_readings_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_equipment_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_risk_discovery_uuid'), table_name='risk_discovery')
    op.drop_index(op.f('ix_risk_discovery_id'), table_name='risk_discovery')
    op.drop_table('risk_discovery')
    op.drop_index(op.f('ix_pattern_relationships_uuid'), table_name='pattern_relationships')
    op.drop_index(op.f('ix_pattern_relationships_id'), table_name='pattern_relationships')
    op.drop_table('pattern_relationships')
    op.drop_index(op.f('ix_optimization_opportunities_uuid'), table_name='optimization_opportunities')
    op.drop_index(op.f('ix_optimization_opportunities_id'), table_name='optimization_opportunities')
    op.drop_table('optimization_opportunities')
    op.drop_index(op.f('ix_maintenance_predictions_id'), table_name='maintenance_predictions')
    op.drop_index(op.f('ix_maintenance_predictions_equipment_id'), table_name='maintenance_predictions')
    op.drop_table('maintenance_predictions')
    op.drop_index(op.f('ix_knowledge_twin_uuid'), table_name='knowledge_twin')
    op.drop_index(op.f('ix_knowledge_twin_id'), table_name='knowledge_twin')
    op.drop_table('knowledge_twin')
    op.drop_index(op.f('ix_knowledge_gap_records_uuid'), table_name='knowledge_gap_records')
    op.drop_index(op.f('ix_knowledge_gap_records_id'), table_name='knowledge_gap_records')
    op.drop_table('knowledge_gap_records')
    op.drop_index(op.f('ix_incident_records_uuid'), table_name='incident_records')
    op.drop_index(op.f('ix_incident_records_id'), table_name='incident_records')
    op.drop_table('incident_records')
    op.drop_index(op.f('ix_expert_knowledge_uuid'), table_name='expert_knowledge')
    op.drop_index(op.f('ix_expert_knowledge_id'), table_name='expert_knowledge')
    op.drop_table('expert_knowledge')
    op.drop_index(op.f('ix_documents_version_group_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_uuid'), table_name='documents')
    op.drop_index(op.f('ix_documents_plant_location'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_department'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_index(op.f('ix_documents_asset_tag'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_decision_recommendations_uuid'), table_name='decision_recommendations')
    op.drop_index(op.f('ix_decision_recommendations_id'), table_name='decision_recommendations')
    op.drop_table('decision_recommendations')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_asset_comparison_uuid'), table_name='asset_comparison')
    op.drop_index(op.f('ix_asset_comparison_id'), table_name='asset_comparison')
    op.drop_table('asset_comparison')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_asset_tag'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_chat_sessions_workspace_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_uuid'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_workspaces_uuid'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_user_organization_grants_id'), table_name='user_organization_grants')
    op.drop_table('user_organization_grants')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_uuid'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_feedback_records_uuid'), table_name='feedback_records')
    op.drop_index(op.f('ix_feedback_records_id'), table_name='feedback_records')
    op.drop_table('feedback_records')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_id'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_audit_logs_uuid'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_departments_uuid'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_plants_uuid'), table_name='plants')
    op.drop_index(op.f('ix_plants_id'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_risk_summary_uuid'), table_name='risk_summary')
    op.drop_index(op.f('ix_risk_summary_id'), table_name='risk_summary')
    op.drop_table('risk_summary')
    op.drop_index(op.f('ix_regulations_uuid'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_name'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_id'), table_name='regulations')
    op.drop_table('regulations')
    op.drop_index(op.f('ix_organizations_uuid'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_model_evaluation_uuid'), table_name='model_evaluation')
    op.drop_index(op.f('ix_model_evaluation_id'), table_name='model_evaluation')
    op.drop_table('model_evaluation')
    op.drop_index(op.f('ix_learning_events_uuid'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_id'), table_name='learning_events')
    op.drop_table('learning_events')
    op.drop_index(op.f('ix_financial_impact_uuid'), table_name='financial_impact')
    op.drop_index(op.f('ix_financial_impact_id'), table_name='financial_impact')
    op.drop_table('financial_impact')
    op.drop_index(op.f('ix_executive_reports_uuid'), table_name='executive_reports')
    op.drop_index(op.f('ix_executive_reports_id'), table_name='executive_reports')
    op.drop_table('executive_reports')
    op.drop_index(op.f('ix_executive_metrics_uuid'), table_name='executive_metrics')
    op.drop_index(op.f('ix_executive_metrics_id'), table_name='executive_metrics')
    op.drop_table('executive_metrics')
    op.drop_index(op.f('ix_enterprise_kpis_uuid'), table_name='enterprise_kpis')
    op.drop_index(op.f('ix_enterprise_kpis_id'), table_name='enterprise_kpis')
    op.drop_table('enterprise_kpis')
    op.drop_index(op.f('ix_discovery_findings_uuid'), table_name='discovery_findings')
    op.drop_index(op.f('ix_discovery_findings_id'), table_name='discovery_findings')
    op.drop_table('discovery_findings')
    op.drop_index(op.f('ix_agent_metrics_uuid'), table_name='agent_metrics')
    op.drop_index(op.f('ix_agent_metrics_id'), table_name='agent_metrics')
    op.drop_index(op.f('ix_agent_metrics_agent_name'), table_name='agent_metrics')
    op.drop_table('agent_metrics')
    op.drop_index(op.f('ix_agent_messages_uuid'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_session_uuid'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_sender'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_receiver'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_agent_memory_uuid'), table_name='agent_memory')
    op.drop_index(op.f('ix_agent_memory_id'), table_name='agent_memory')
    op.drop_index(op.f('ix_agent_memory_agent_name'), table_name='agent_memory')
    op.drop_table('agent_memory')
    op.drop_index(op.f('ix_agent_collaboration_uuid'), table_name='agent_collaboration')
    op.drop_index(op.f('ix_agent_collaboration_session_uuid'), table_name='agent_collaboration')
    op.drop_index(op.f('ix_agent_collaboration_id'), table_name='agent_collaboration')
    op.drop_table('agent_collaboration')
    # ### end Alembic commands ###
